import Head from "next/head";
import Image from "next/image";
import { Rubik } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "@/components/Card";
import MainCard from "@/components/MainCard";

const rubik = Rubik({ subsets: ["latin"], weight: ["300", "400", "500"] });

export type CardType = {
  cardName: string;
  title: string;
  current: number;
  previous: number;
  units: "hrs" | "mins";
  color: string;
  icon: string;
  link: string;
};

const cards: CardType[] = [
  {
    cardName: "work",
    title: "Work",
    current: 32,
    previous: 36,
    units: "hrs",
    color: "light-orange",
    icon: "/images/icon-work.svg",
    link: "/work",
  },
  {
    cardName: "play",
    title: "Play",
    current: 10,
    previous: 12,
    units: "hrs",
    color: "soft-blue",
    icon: "/images/icon-play.svg",
    link: "/play",
  },
  {
    cardName: "study",
    title: "Study",
    current: 4,
    previous: 7,
    units: "hrs",
    color: "light-red",
    icon: "/images/icon-study.svg",
    link: "/study",
  },
  {
    cardName: "exercise",
    title: "Exercise",
    current: 4,
    previous: 5,
    units: "hrs",
    color: "lime-green",
    icon: "/images/icon-exercise.svg",
    link: "/exercise",
  },
  {
    cardName: "social",
    title: "Social",
    current: 1,
    previous: 3,
    units: "hrs",
    color: "violet",
    icon: "/images/icon-social.svg",
    link: "/social",
  },
  {
    cardName: "self-care",
    title: "Self Care",
    current: 0,
    previous: 1,
    units: "hrs",
    color: "soft-orange",
    icon: "/images/icon-self-care.svg",
    link: "/self-care",
  },
];

const mainInfo = {
  userName: "Jeremy Robson",
  cardName: "main-card",
  color: "blue",
  avatarSrc: "/images/image-jeremy.png",
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Time tracking dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${rubik.className} centered`}>
        <div className={styles["card-grid"]}>
          <MainCard
            userName={mainInfo.userName}
            cardName={mainInfo.cardName}
            color={mainInfo.color}
            avatarSrc={mainInfo.avatarSrc}
          />
          {cards.map((card) => (
            <Card
              key={card.cardName}
              cardName={card.cardName}
              title={card.title}
              current={card.current}
              previous={card.previous}
              units={card.units}
              color={card.color}
              icon={card.icon}
              link={card.link}
            />
          ))}
        </div>
      </main>
    </>
  );
}
