import Head from "next/head";
import Image from "next/image";
import { Rubik } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "@/components/Card";
import MainCard from "@/components/MainCard";
import { useEffect, useState } from "react";
import { Activity } from "./api/profile";

const rubik = Rubik({ subsets: ["latin"], weight: ["300", "400", "500"] });

export type CardType = {
  cardName: string;
  title: string;
  current: number;
  previous: number;
  units: "hrs" | "mins";
  color: string;
  icon: string;
  link: string;
};

const mainInfo = {
  userName: "Jeremy Robson",
  cardName: "main-card",
  color: "blue",
  avatarSrc: "/images/image-jeremy.png",
};

export default function Home() {
  const [data, setData] = useState<Activity[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [period, setPeriod] = useState<"daily" | "weekly" | "monthly">("daily");

  useEffect(() => {
    setIsLoading(true);
    fetch("/api/profile")
      .then((res) => res.json())
      .then((data) => {
        setData(data);
        setIsLoading(false);
      })
      .catch((err) => {
        console.log(err);
        setIsLoading(false);
      });
  }, []);

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Time tracking dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${rubik.className} centered`}>
        <div className={styles["card-grid"]}>
          <MainCard
            userName={mainInfo.userName}
            cardName={mainInfo.cardName}
            color={mainInfo.color}
            avatarSrc={mainInfo.avatarSrc}
            selectedPeriod={period}
            setSelectedPeriod={setPeriod}
          />
          {data.map((card) => (
            <Card
              key={card.title}
              cardName={card.title.replace(' ', '').toLowerCase()}
              title={card.title}
              current={card.timeframes[period].current}
              previous={card.timeframes[period].previous}
              units={'hrs'}
              color={card.color}
              icon={card.icon}
              link='#'
            />
          ))}
        </div>
      </main>
    </>
  );
}
